flutter_icons:

  #after any updates to this file
  # RUN => flutter pub run flutter_launcher_icons:main -f launcher_icon_config.yaml

  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true